### ISSUE TITLE
it dosn't work now :(

### ISSUE THREAD

**Issue by 7788lx** [ultrasev/cursor-reset#2]

**Comment by ultrasev** [comment]
Doen't work how ?

**Comment by bugrevealingbme** [comment]
yeah not working

**Comment by ultrasev** [comment]
> yeah not working on mac

You need to logout and quit  cursor completely before using this script.

**Comment by zw-store** [comment]
> > 是的，在 Mac 上不起作用
> 
> 在使用此脚本之前，您需要完全注销并退出光标。

邮箱需要换新的邮箱吗，还是说只是注销登录就行了。

**Comment by ultrasev** [comment]
> > > 是的，在 Mac 上不起作用
> > 
> > 
> > 在使用此脚本之前，您需要完全注销并退出光标。
> 
> 邮箱需要换新的邮箱吗，还是说只是注销登录就行了。

如果是试用的话，先退出账号， 再完全退出 cursor 编辑器，后台也杀掉。
然后运行脚本。 
再然后重新打开 cursor，注册并登录即可。
我昨天还在用，如果还有问题，麻烦提供 cursor 返回的信息，我研究一下。
